weight_val: .1 
k_val: 250 
proposal_temp: .1
use_diverse_initialization: false
use_cnn_batchloss: false 
filter_type: topk
p_val: 0.9
filter_logit: dist
bias_compute_method: penalty
weight_strat: learn
min_weight: 1.0
max_weight: 1.0
weight_lr: 1e-3
bias_rep_space: embed
use_scale_based_weight: true 
