weight_val: 1.15 
k_val: 250 
proposal_temp: .1
initialization: zero 
min_weight: 1.0
max_weight: 1.0
use_bolt_weights: false
use_scale_weights: true
initialization_noise_rate: .5
use_soft_disc: true
is_multi: false