default:
  bias_rep_space: embed 
  proposal_rep_space: embed
  step_size: 1.0 
weight_val: 
  values: [.1, .15, .2]
k_val: 
  values: [50, 100, 250, 500, 1000]
proposal_temp: 
  values: [.01, .05, .1, .5, 1.0]
disc_weight: 
  values: [.1, .2, .3,.4, .5, .6, .7, .8, .9]
use_bolt_weights:
  values: [true, false]
use_scale_weights:
  values: [true, false]
step_size: 
  values: [.05, .1, .25, .5, 1.0, 2.0]