default: 
  bias_rep_space: logit
  proposal_rep_space: logit
  k_val: 250 
  disc_weight: .01
  use_bolt_weights: true
  use_scale_weights: true
  weight_val: 1.0
  initialization: kw
weight_val: 
  values: [1.0, 1.2, 1.3, 1.4, 1.5]
proposal_temp: 
  values: [.00001, .0001, .001, .01, .1]
disc_weight: 
  values: [.1, .2, .3,.4, .5, .6, .7, .8, .9]
initialization: 
  values: [random_cont, random_disc, kw]
