base_model_args: 
  n_tokens: 10 
  initialize_from_vocab: true 
  use_full_prompt: false
  pretrained_model_name_or_path: gpt2-large
sentiment_prompts: prompts/sentiment_prompts_15.txt 
detoxic_prompts: prompts/detoxic_prompts_1k.txt
keyword_prompts: prompts/keywords_prompts_15.txt
batch_size: 20
seq_len: 20
num_steps: 20
sentiment: pos
keywords_dict:
  computer : ["router", "Linux", "keyboard", "server"]
  legal : ["plea", "subpoena", "transcript", "bankrupt"]
  military : ["torpedo", "headquarters", "infantry", "battlefield"]
  politics : ["court", "culture", "communism", "capitalism"]
  religion : ["Bible", "church", "priest", "saint"]
  science : ["microscope", "mass", "mineral", "scientist"]
  space : ["meteor", "planet", "satellite", "astronaut"]
keyword: computer
abductive_reasoning_file: prompts/anli/test.jsonl
early_stop: true